### ISSUE TITLE
An error:multidir

### ISSUE THREAD

**Issue by GoldyMark** [spongessuck/gm.datepickerMultiSelect#7]
An error occurs.My angularjs version is 1.2.20.

```
 Error: [$compile:multidir] http://errors.angularjs.org/1.2.20/$compile/multidir?p0=datepicker&p1=multi…s%3D%22date-picker%22%20ng-model%3D%22date%22%20multi-select%3D%22sd%22%3E
    at Error (native)
    at file:///E:/FF9/js/libs/angular.min.js:6:450
    at I (file:///E:/FF9/js/libs/angular.min.js:61:486)
    at H (file:///E:/FF9/js/libs/angular.min.js:55:342)
    at file:///E:/FF9/js/libs/angular.min.js:60:324
    at file:///E:/FF9/js/libs/angular.min.js:72:199
    at J (file:///E:/FF9/js/libs/angular.min.js:99:469)
    at J (file:///E:/FF9/js/libs/angular.min.js:99:469)
    at file:///E:/FF9/js/libs/angular.min.js:101:126
    at k.$eval (file:///E:/FF9/js/libs/angular.min.js:111:353)
```

**Comment by spongessuck** [comment]
Can you post your source or a demo? It looks like you're not adding the directive to your datepicker properly.
